Handle SIGINT and SIGTERM in configure-ovs
However unlikely, it is possible that configure-ovs receives any of
these signals and either ignores them or terminates midway with an
inconsistent configuration requiring manual intervention to recover.

Handle these signals by attempting to rollback any configuration changes
performed and exiting with a sensible exit code.

Signed-off-by: Jaime Caamaño Ruiz <jcaamano@redhat.com>

diff --git a/templates/common/_base/files/configure-ovs-network.yaml b/templates/common/_base/files/configure-ovs-network.yaml
--- a/templates/common/_base/files/configure-ovs-network.yaml
+++ b/templates/common/_base/files/configure-ovs-network.yaml
@@ -98,7 +98,7 @@ contents:
       old_name="$(nmcli -g connection.id connection show uuid "$uuid")"
       local new_name="${old_name}${MANAGED_NM_CONN_SUFFIX}"
       if nmcli connection show id "${new_name}" &> /dev/null; then
-        echo "WARN: existing ovs slave ${new_name} connection profile file found, overwriting..." >&2
+        echo "WARNING: existing ovs slave ${new_name} connection profile file found, overwriting..." >&2
         nmcli connection delete id "${new_name}" &> /dev/null
       fi
       nmcli connection clone $uuid "${new_name}" &> /dev/null
@@ -307,7 +307,7 @@ contents:
       # Warn about an invalid MTU that will most likely fail in one way or
       # another
       if [ ${iface_mtu} -lt 1280 ] && [ "${ipv6_method}" != "disabled" ]; then
-        echo "Warning: MTU ${iface_mtu} is lower than the minimum required of 1280 for IPv6"
+        echo "WARNING: MTU ${iface_mtu} is lower than the minimum required of 1280 for IPv6"
       fi
 
       if ! nmcli connection show "$ovs_interface" &> /dev/null; then
@@ -459,7 +459,7 @@ contents:
 
         echo "Waiting for interface $dev to activate..."
         if ! timeout 60 bash -c "while ! nmcli -g DEVICE,STATE c | grep "'"'"$dev":activated'"'"; do sleep 5; done"; then
-          echo "Warning: $dev did not activate"
+          echo "WARNING: $dev did not activate"
         fi
       done
 
@@ -815,10 +815,28 @@ contents:
       exit $e
     }
 
+    # We will use a standard 128 + SIGTERM (15) exit code when terminated
+    TERM_EXIT_CODE=143
+    # We will use a standard 128 + SIGINT (2) exit code when interrupted
+    INT_EXIT_CODE=130
+    
+    # Setup a signal trap to rollback
+    handle_signal() {
+      echo "WARNING: configure-ovs has been requested to terminate"
+      
+      # by exiting with the signal error we will cleanup after ourselves in the
+      # subsequent call to handle_exit
+      exit "$1"
+    }
+
     # main function
     configure_ovs() {
       set -eu
-      trap "handle_exit" EXIT
+
+      # setup traps to handle signals and other abnormal exits
+      trap 'handle_signal $TERM_EXIT_CODE' TERM
+      trap 'handle_signal $INT_EXIT_CODE' INT
+      trap 'handle_exit' EXIT
 
       # this flag tracks if any config change was made
       nm_config_changed=0
@@ -836,7 +854,7 @@ contents:
       fi
 
       if ! rpm -qa | grep -q openvswitch; then
-        echo "Warning: Openvswitch package is not installed!"
+        echo "WARNING: Openvswitch package is not installed!"
         exit 1
       fi
 
@@ -989,8 +1007,15 @@ contents:
       # Run configure_ovs in a sub-shell
       ( configure_ovs "$@" )
       e=$?
-      [ "$e" -eq 0 ] || [ -z "$RETRY" ] && exit "$e"
-      echo "configure_ovs failed, will retry after $RETRY"
+      
+      # succesful termination
+      [ "$e" -eq 0 ] && exit "$e"
+      # abnormal termination, iterrupted with a signal
+      [ "$e" -eq $TERM_EXIT_CODE ] || [ "$e" -eq $INT_EXIT_CODE ] && exit "$e"
+      # abnormal termination, configured not to retry
+      [ -z "$RETRY" ] && exit "$e"
+      
+      echo "configure-ovs failed, will retry after $RETRY"
       # flag that a retry has happened
       touch /tmp/configure-ovs-retry
       sleep "$RETRY"
